local X = {}

X.Trashtalks = {
  Offensive = { 
    "Marek zase feedi", 
    "Filipko uz ide spat",
    "Hras ako moja stara mama",
    "Mal by si najskor skusit tutorial a potom hrat proti mne",
    "Čo sa to deje? Nevedel si, že hra začala?",
    "Ty by si mal skôr ísť hrať Tetris.",
    "Som rád, že mám takého dobrého kamaráta, ktorý mi dáva killi.",
    "Ty by si mal skúsiť hrať hru pre menej náročných hráčov."  ,
      "Tvoj skill level sa pohybuje medzi nulou a ničom.",
    "Kde si sa to naučil hrať? Na svojom telefóne?",
    "Ty by si mal radšej ísť farmovať, namiesto toho, aby si sa pokúšal bojovať.",
    "Môj pes dokáže hrať lepšie ako ty.",
    "Vidím, že si stále vo svojej bubline.",
    "Ty si v tom horší ako bambus v šachu.",
    "Ak by som bol na tvojom mieste, radšej by som sa skryl.",
    "S tvojím skill levelom si môžeš skôr zahrať Candy Crush ako Dota 2.",
    "Ak chceš vyhrať, musíš sa naučiť hrať, nie iba kliknúť na tlačidlo.",
      "Aké to musí byť, hrať proti vám a nebyť ani výzvou.",
    "Nemal by si hrať s počítačom namiesto toho, aby si tu vyrábala svoje umenie.",
    "Ak by si mala aspoň polovicu môjho skill levelu, bolo by to zaujímavé.",
    "Myslím, že by si mala ísť radšej hrať Tetris, to by ti mohlo vyhovovať.",
     "Tvoje zručnosti sú také nízke, že vyzeráš ako robot s Downovým syndrómom.",
    "Ak by to bola olympiáda, získala by si zlatú medailu v kategórii najhorší hráč.",
    "Myslím, že by si sa mal snažiť hrať s jedným okom uzavretým, možno by si bol lepší.",
    "Tvoje stratégie je taká zlá, že by som ju mohol opísať ako 'nechať sa zabiť'.",
    "Tvoj skill level je tak nízky, že by som ťa mohol poraziť s jedným prstom.",
    "Ak by sme hrali kategóriu najhorší hráč, vyhral by si bez problémov.",
    "Myslím, že by si mal radšej ísť hrať hry pre deti, tam by ti to možno išlo lepšie.",
    "Ak by si bol taký dobrý, ako si myslíš, určite by si už bol vyhral.",
     "Myslel som si, že budeš oveľa lepší ako to, čo som práve videl.",
    "Hral si tak zle, že som si už začínal myslieť, že to robíš schválne.",
    "Môžeš byť rád, že hrať proti tebe nie je vôbec náročné.",
    "Pridaj si niektoré lekcie základnej hry, pretože tvoje výkony sú úplne tragické.",
    "Máš taký slabý skill, že by si v Dota 2 mohol hrať iba ako tréningový panák.",
     "Filipko, aj keď by si sa snažil, neporazil by si ani cvoka.",
    "Marek, ako sa to robí, nevieš, ale ako sa to nerobí, vieš určite.",
    "Ganjalf, tvoja strategická schopnosť je rovnaká ako schopnosť tvrdiť, že Mordor je pekné miesto.",
    "Pejko, ak by sa hralo na to, kto najviac feedne, ty by si rozhodne vyhral.",
    "Cvok, z tvojej hry mám pocit, akoby si bol ovládaný nejakou zlou silou."    ,
    "Filipko, tvoje hry mi prídu ako predstavenie šíleného klauna.",
    "Marek, tvoje hranie sa mi javí ako úmyselný sabotáž.",
    "Ganjalf, tvoje postavy sa pohybujú ako hromada kameňov.",
    "Pejko, tvoje feedovanie nás ťahá dolu ako olovený balvan.",
    "Cvok, tvoj výkon je katastrofálny ako zemetrasenie.",
     "Filipko, tvoje hranie je horšie ako keby ti ovládanie ovládali mačky.",
    "Marek, tvoj skill je taký nízky, že by si sa v hre mal volať Marek Low-ry.",
    "Ganjalf, keby tvoju hru mala ohodnotiť, určite by si nedostal viac ako 2 z 10 bodov.",
    "Pejko, tvoje hranie je ako zlý sen, z ktorého sa nedokážeš prebudiť.",
    "Cvok, tvoje výkony sú na úrovni základnej školy, a to myslím tá najsprostejšia.",
      "Už si si zvykol byť vždy feedom, Marek?",
    "Chcel by som ťa poraziť v niečom inom, Pejko, pretože v Dota 2 si na to zjavne nevystačíš.",
    "Ganjalf, ak by si chcel zvýšiť svoj skill, tak si najskôr musíš zlepšiť svoje myšlienky.",
    "Cvok, máš šancu sa so mnou učiť alebo sa učiť od svojich chýb.",
    "Marek, ak budeš pokračovať v takých výkonoch, tak skôr či neskôr sa ti v Dota 2 úplne stratia všetky body.",
      "Vidím, že si stále rovnaký, Filipko, či už ide o tvoj vzhľad alebo hru.",
    "Ganjalf, ak by sa Dota 2 hodnotila podľa tvojho výkonu, tak by bola najhoršou hrou všetkých čias.",
    "Cvok, ak si chcel hrať len sám proti sebe, tak si nemusel vôbec prihlásiť do hry.",
    "Pejko, skúšal si niekedy hrať s priateľmi, aby si videl, ako sa to robí?",
    "Marek, tvoje výkony v hre sú horšie ako tvoja gramatika.",
     "Filipko, ja by som sa fakt hanbil, keby som hral tak zle ako ty.",
    "Ganjalf, ak by som mal hráča ako ty v tíme, radšej by som hral s botmi.",
    "Cvok, ak sa snažíš hrať na retardovaného hráča, tak ti to fakt dobre ide.",
    "Pejko, vieš, že by si sa našiel skvelo v tíme pre začiatočníkov?",
    "Marek, tvoja hra ma neuspokojuje, a to už hovorím úplne slušne.",
      "Filipko, ty si horší ako boti, ktorí hrajú na easy.",
    "Ganjalf, s tvojou hrou by sme mohli vyhrať cenu za najhorší tím.",
    "Cvok, mohol by si si dať trochu pauzu a pozrieť si nejaké návody na YouTube.",
    "Pejko, tvoja hra mi pripomína moje staré babičky, ktoré hrali na počítači iba s pomocou myši.",
    "Marek, som rád, že si ma zobral do tímu, pretože teraz mám šancu byť najlepší.",
        "Marek, toto nie je hra pre teba. Možno by si si mal radšej zahrať Tetris.",
    "Ganjalf, ty si taký noob, že sa mi až nechce hrať.",
    "Pejko, ja by som skôr zahral s mojím mŕtvym psom ako s tebou.",
    "Cvok, tvoja hra je taká slabošská, že sa ti asi ani nedá hrať proti botom.",
    "Filipko, ja neviem, čo robíš, ale zrejme to nie je dobre."
  }, 
  Defensive = {
    "Prepac ja som nechcel", 
    "Preco by si to robil", 
    "Ved sme kamarati", 
    "Ved ty pockaj ja viem kde byvas", 
    "sa neposerte",
     "Ja som sa len pokúsil niečo urobiť pre tím.",
    "Prečo sa tak hneváš? To je len hra.",
    "Ja som ti nič zlé nechcel.",
    "Ostali sme si aspoň verní svojim skillovým levelom.",
     "Neboj sa, nevyruším ťa viac počas hry.",
    "Viem, že to bol môj zlyhanie, skúsime to lepšie nabudúce.",
    "Aj keď sme na opačných stranách, máme rovnaký cieľ - vyhrať hru.",
    "Nemám záujem hrať proti hráčom, ktorí nechápu fair play.",
    "Nemyslel som si, že to takto dopadne, ale som ochotný sa poučiť.",
    "Viem, že si sa snažil, gratulujem ti za to.",
    "Myslím, že by sme sa mali sústrediť na to, ako hrať tímovo.",
    "Niekedy sa to proste takto vyvinie, nič s tým neurobíme.",
    "Ja som nebol pripravený na tvoj skvostný plán.",
    "Neviem, čo sa stalo, ale budeme sa snažiť to napraviť.",
    "Som prekvapený tým, ako rýchlo si sa naučila hrať.",
    "Vidím, že si pekný súper, budem sa musieť viac snažiť.",
     "Som rád, že mám v tvojom tíme niekoho, kto sa dokáže držať aj v ťažkých situáciách.",
    "Je v poriadku robiť chyby, to je súčasť učenia sa.",
    "Napriek tomu, že sme prehrali, myslím, že sme hrali dobre ako tím.",
    "Snažil som sa, ale musím sa ešte veľa učiť.",
     "Myslím, že som sa snažil, ale moje rozhodnutia boli chybné.",
    "Hral som dobre, ale musím sa ešte zlepšiť.",
    "Vidím, že si veľmi skúsený, musím sa viac snažiť, aby som ťa dokázal poraziť.",
    "Je ťažké hrať proti takým dobrým hráčom ako ty, ale budem sa snažiť.",
     "Nechcem byť pre teba príliš tvrdý, iba sa snažím nájsť spôsob, ako sa môžeme zlepšiť.",
    "Určite vieš, že to, čo som práve povedal, bolo len žart, že?",
    "Nechajme minulosť za sebou a skúsme sa zamerať na to, ako sa môžeme stať lepšími hráčmi.",
    "Prepáč, ak som ťa niečim urazil, to nebolo mojím zámerom.",
    "Som presvedčený, že spolu môžeme dosiahnuť skvelé výsledky, ak budeme spolupracovať.",
     "Viem, že som urobil chybu, Filipko, ale urobím všetko preto, aby som ju napravil.",
    "Marek, dnes to nevyšlo, ale zajtra to bude lepšie, súhlasíš?",
    "Ganjalf, viem, že si sa snažil a to je dôležité, ďalšíkrát to určite bude lepšie.",
    "Pejko, chyby sa stávajú každému, nič zlé sa nestalo.",
    "Cvok, nezúfaj, určite sa ešte budeš zlepšovať.",
      "Prepáč, Filipko, nechcel som ťa uraziť, iba som sa snažil trochu nadsádzať.",
    "Marek, neber si to osobne, iba som sa chcel trochu pohrať s tvojou nervovou sústavou.",
    "Ganjalf, nechcem ťa uraziť, len som sa snažil trochu podráždiť tvoj zmysel pre humor.",
    "Pejko, prepáč, ak som ťa urazil, to nebolo mojím zámerom.",
    "Cvok, nezúfaj, iba som sa snažil trochu zvýšiť atmosféru.",
     "Prepáč, Filipko, nechcel som ťa uraziť, iba som sa snažil trochu nadsádzať.",
    "Marek, neber si to osobne, iba som sa snažil trochu pohrať s tvojou nervovou sústavou.",
    "Ganjalf, nechcem ťa uraziť, len som sa snažil trochu podráždiť tvoj zmysel pre humor.",
    "Pejko, prepáč, ak som ťa urazil, to nebolo mojím zámerom.",
    "Cvok, nezúfaj, iba som sa snažil trochu zvýšiť atmosféru.",
     "Nemyslel som to osobne, Filipko, skôr som chcel vyzvať na zlepšenie našich výkonov.",
    "Ganjalf, nenechaj sa odradiť mojím predošlým výrokom, verím, že si skvelý hráč.",
    "Cvok, bol to iba náhodný komentár, nič osobné.",
    "Pejko, nezúfaj, aj ja som začínal s chybnými krokmi, ale naučil som sa z nich.",
    "Marek, možno som sa prehnal, prepáč mi to.",
  "Prepáč, Filipko, to bolo nevhodné, už sa to nezopakuje.",
    "Ganjalf, myslím si, že si lepší hráč, než ako som to naznačil, bol to iba môj názor.",
    "Cvok, neber to osobne, bol to iba náš nezdar v hre.",
    "Pejko, ďakujem ti za skvelý zápas, bolo to veľmi zaujímavé.",
    "Marek, nechajme stranou naše nezhody a sústreďme sa na hru.",
     "Filipko, ja nechcem urážať tvoju hru, len hovorím, čo si myslím.",
    "Ganjalf, ja nechcem byť zlým chalanom, len hovorím pravdu.",
    "Cvok, neviem, ako sa to mohlo stať, bolo to iba zlé šťastie.",
    "Pejko, ja nechcem byť príliš tvrdý na teba, bolo to len nešťastie.",
    "Marek, ja nechcem ťať na tvoju hru, len ma to trochu zaskočilo.",
       "Filipko, ja si neviem predstaviť, že by si na môjom mieste hral lepšie.",
    "Ganjalf, ja si myslím, že máme iba rôzne hry, preto sa nechcem hádať.",
    "Cvok, ja nechcem byť negatívny, ale mohol by si trochu popracovať na svojej hre.",
    "Pejko, mohol by si mi poradiť, ako sa lepšie zlepšiť v hre?",
    "Marek, ja viem, že tvoja hra je na vyššej úrovni ako moja, preto sa nechcem príliš rozprávať.",
   "Marek, ja som sa len pokúsil zahrať to najlepšie ako viem.",
    "Ganjalf, nechcem s tebou hádať, skúsme sa radšej zamerať na hru.",
    "Pejko, ja nechcem tvojou hrou nikoho rušiť, iba sa snažím byť čo najlepší.",
    "Cvok, ja si myslím, že každý sa snaží robiť čo najlepšie, a ty si určite nie výnimkou.",
    "Filipko, nechcem nikoho urážať, skúsim sa sústrediť na svoju hru."
  }, 
  Neutral = {
    "Kudus na hrad", 
    "jeden McFirstBlood poprosim", 
    "Choj uz spat", 
    "Musime chodit spolu", 
    "Ja idem spat",
        "To bol kus šťastia.",
    "Dobre hrané, súper.",
    "Vidíš, keď sa tím spojí, tak to ide.",
    "Myslím, že by sme sa mali sústrediť na hru.",
    "Hra je ako život, plná prekvapení a nečakaných zvratov.",
    "Naučil som sa, že nezáleží na tom, či vyhráš alebo prehráš, ale na tom, ako si sa snažil.",
    "Som rád, že môžem hrať s dobrými hráčmi, ako si ty.",
    "Ak chceš byť dobrý v niečom, musíš to robiť každý deň a snažiť sa zlepšovať.",
    "Vidím, že sa učíš, držím ti palce.",
    "Hrať s dobrými hráčmi je najlepší spôsob, ako sa zlepšovať.",
    "Každá hra je príležitosťou naučiť sa niečo nové.",
    "Dúfam, že tieto skúsenosti nám pomôžu v budúcnosti.",
    "Každá hra je iná, musíme sa prispôsobiť.",
    "Všetci môžeme mať zlý deň, dôležité je, aby sme sa z toho poučili.",
    "Som rád, že môžeme hrať spolu.",
    "Nikdy nie je neskoro začať sa učiť niečo nové.",
    "Dnes je miesto, kde sa môžeš naučiť niečo nové.",
    "Hrať proti skúseným hráčom je pre mňa skvelou príležitosťou zlepšiť sa.",
    "Myslím, že by sme sa mali sústrediť na to, ako zlepšiť našu spoluprácu ako tím.",
    "Vidím, že si sa zlepšila od poslednej hry, gratulujem ti k tomu.",
    "Myslím, že by sme sa mali viac sústrediť na tím a spoluprácu.",
    "Nemusíš sa cítiť zle, hrať proti dobrým hráč",
    "Som si istý, že s trochou tréningu a tvrdej práce by si mohol byť veľmi úspešný v Dota 2.",
    "Vidím, že máš veľa potenciálu a som zvedavý, ako ho budeš dokázať využiť.",
    "Nie je to iba o výhre alebo prehre, ide o to, aby sme si z hry užili čo najviac.",
    "Každá prehra je pre nás príležitosťou naučiť sa niečo nové.",
    "Vedz, že som tu pre teba, ak budeš potrebovať radu alebo pomoc v hre.",
    "Filipko, máš niektoré dobré nápady, ak by si ich zdieľal s ostatnými, mohli by sme sa zlepšiť.",
    "Marek, som rád, že sme v tíme spolu, dokážeme spolu veľa dosiahnuť.",
    "Ganjalf, verím, že tvoje skúsenosti nám budú prospievať ako tímu.",
    "Pejko, hrať s tebou je zábava, verím, že budeme mať aj v budúcnosti veľa dobrých hier.",
    "Cvok, viem, že nemusíš byť najlepší hráč, ale aj tak si dôležitý pre náš tím.",
    "Filipko, máš dobrý potenciál, verím, že sa ešte môžeš zlepšiť.",
    "Marek, verím, že tvoja hra sa bude zlepšovať s každou ďalšou hrou.",
    "Ganjalf, tvoje poznatky o hre môžu byť pre nás veľmi užitočné.",
    "Pejko, naše výkony sa líšia, ale spoločne môžeme dosiahnuť veľké veci.",
    "Cvok, aj keď si nie vždy najlepší hráč, tvoja ochota pomáhať nám veľa znamená.",
    "Filipko, ak by si sa zameral na tréning, mohol by si sa stať výborným hráčom.",
    "Marek, aj keď sme sa práve prehrali, som si istý, že tvoj skill sa bude len zlepšovať.",
    "Ganjalf, máš dobré potenciál, ak sa budeš snažiť, môžeš sa stať vynikajúcim hráčom.",
    "Pejko, tvoj prístup k hre je obdivuhodný, verím, že sa ti podarí dosiahnuť svoje ciele.",
    "Cvok, naša tímová spolupráca sa bude len zlepšovať, ak budeme pracovať na svojich slabých stránkach.",
    "Je skvelé hrať s tebou, Filipko, pretože vždy sa od teba dá niečo nové naučiť.",
    "Ganjalf, mám pocit, že spolu môžeme vytvoriť skvelý tím, ak budeme spolupracovať.",
    "Cvok, vidím, že si sa zlepšil v niektorých aspektoch hry, skúsme to udržať.",
    "Pejko, aj keď sme súpermi v hre, som rád, že sme mohli spolu hrať.",
    "Marek, teším sa, že ťa vidím na ceste k zlepšeniu sa v hre.",
    "Filipko, vidím, že máš zaujímavý herný štýl, rád by som sa s tebou stretol aj v iných hrách.",
    "Ganjalf, máš zaujímavé strategické myslenie, musíme si dať nejaký iný zápas.",
    "Cvok, vidím, že sa stále snažíš zlepšovať, veľmi ti to prajem.",
    "Pejko, ak by si mal záujem, môžeme si urobiť tímovku, aby sme sa mohli poriadne porovnať.",
    "Marek, vidím, že sa učíš z každej hry, to je veľmi dôležité pre tvôj rozvoj.",
    "Filipko, vieš, že by si sa u nás našiel skvelo, máme veľa skúsených hráčov.",
    "Ganjalf, tvoja hra je zaujímavá, mal by si sa pripojiť k nášmu tímu.",
    "Cvok, vieš, že som si všimol, že sa veľa snažíš, to je dobré.",
    "Pejko, výborný zápas, rád by som si to zopakoval.",
    "Marek, vidím, že si sa skutočne zlepšil, bolo to veľmi zaujímavé.",
    "Filipko, čo hovoríš na to, ak si niekedy zahráme v tíme?",
    "Ganjalf, vieš, že by som sa rád niečo od teba naučil, pretože tvoja hra je skvelá.",
    "Cvok, hral si niekedy na turnaji? Bolo by to super, keby sme tam mohli hrať spolu.",
    "Pejko, čo hovoríš na to, ak sa zahrajeme spolu aj niekedy inokedy?",
    "Marek, ak by si mal niekedy čas, bolo by super zahrať si spolu v tíme.",
    "Marek, čo by si povedal na to, ak by sme zahrali proti sebe, ale len tak pre zábavu?",
    "Ganjalf, ja si myslím, že by si mohol byť dobrý tréner pre niekoho, kto sa učí hrať.",
    "Pejko, čo hovoríš na to, ak si niekedy zahráme aj niečo iné ako Dota?",
    "Cvok, ak by si mal niekedy nejaké rady alebo tipy, určite by som ich ocenil.",
    "Filipko, čo hovoríš na to, ak sa spolu niekedy pozrieme na niektoré zápasy z Dota majstrovstiev?"
  }
}

function X.getTrashtalk(table_name)
  local used = {}
  local function getNext()
    local items = {}
    for i,v in ipairs(X.Trashtalks[table_name]) do
      if not used[v] then
        table.insert(items, v)
      end
    end
    if #items == 0 then
      for i,v in ipairs(X.Trashtalks[table_name]) do
        used[v] = nil
      end
      items = X.Trashtalks[table_name]
    end
    local index = RandomInt(1, #items);
    local item = items[index]
    used[item] = true
    return item
  end
  return getNext
end

return X
